# Generated by Django 5.1.2 on 2025-11-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fisiologis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmssd', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('spo2', models.FloatField()),
                ('pnn50', models.FloatField()),
                ('sdrr', models.FloatField()),
            ],
        ),
    ]
