# Generated by Django 5.1.2 on 2025-11-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251128_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisiologis',
            name='label',
            field=models.IntegerField(default=0),
        ),
    ]
