# Generated by Django 5.1.2 on 2025-11-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fisiologis_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisiologis',
            name='predict_cluster',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fisiologis',
            name='label',
            field=models.IntegerField(null=True),
        ),
    ]
