# Generated by Django 5.1.2 on 2025-11-28 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fisiologis_predict_cluster_alter_fisiologis_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisiologis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fisiologis',
            name='label',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
